name: validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: lfenergy/arras:develop

    steps:
    - uses: actions/checkout@v3

    - name: Build module
      run: echo "cd source; make install" | gridlabd shell

    - name: Validate module
      run: gridlabd --validate
        
    - name: Upload artifacts on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: validate-result
        path: |
          validate.txt
          autotest/
